// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://buulyuwclleoagspfegz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1dWx5dXdjbGxlb2Fnc3BmZWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyOTc3MjMsImV4cCI6MjA0Nzg3MzcyM30.dl8QCudLeaO6dbFaG-goszqlbn_fNaKJjHvlggL70_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);